name: Enforce Merges to Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-branch-strategy:
    runs-on: ubuntu-latest

    steps:
    - name: Ensure PR is from stage branch
      run: |
        if [ "${{ github.head_ref }}" != "staged" ]; then
          echo "Error: Pull requests to the 'main' branch can only be merged from the 'staged' branch.";
          exit 1;
        fi
