name: Build Docker Image on Release UI

on:
  release:
    types: [created] # Triggers when a new release is created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Path to your Dockerfile
          push: true # Set to true if you want to push the image to a registry
          tags: ${{ secrets.DOCKER_USERNAME }}/subasta-ui:${{ github.ref_name }} # Use the release tag as the image tag
