name: Build Docker Image on Release UI

on:
  release:
    types: [created] # Triggers when a new release is created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile # Path to your Dockerfile
          push: true # Set to true if you want to push the image to a registry
          tags: ${{ secrets.DOCKER_USERNAME }}/subasta-ui:${{ github.ref_name }} # Use the release tag as the image tag

      - name: Clone second repository
        run: |
          git clone https://github.com/paulon-zervoulakus/kubernetes-argocd-bidding.git
          cd kubernetes-argocd-bidding

      - name: Update YAML file
        run: |
          cd kubernetes-argocd-bidding
          sed -i "s|image: .*|image: paulonzervoulakus/subasta-ui:${{ github.event.release.tag_name }}|g" deployment-ui.yaml

      - name: Commit and push changes
        run: |
          cd kubernetes-argocd-bidding
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add deployment-ui.yaml
          git commit -m "Update blueprint file for release ${{ github.event.release.tag_name }}"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/paulon-zervoulakus/kubernetes-argocd-bidding.git HEAD:main
