name: Enforce Merges to Release Branch

on:
  pull_request:
    branches:
      - stage

jobs:
  enforce-branch-strategy:
    runs-on: ubuntu-latest

    steps:
    - name: Ensure PR is from features or hotfix or bugfix branch
      run:  |
        if [[ "${{ github.head_ref }}" == feature/* ]]; then
          echo "Pull request is from a feature branch, proceeding.";
        elif [[ "${{ github.head_ref }}" == hotfix/* ]]; then
          echo "Pull request is from a hotfix branch, proceeding.";
        elif [[ "${{ github.head_ref }}" == bugfix/* ]]; then
          echo "Pull request is from a bugfix branch, proceeding.";
        else
          echo "Error: Pull requests to the 'stage' branch can only be merged from 'features/*' or 'hotfix/*' branches.";
          exit 1;
        fi
